# This file is intended to be run in /home/pi/edgar on RaspberryPi
services:
  edgar:
    image: edgar
    container_name: edgar
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - JAR_SOURCE_PATH=./app.jar
        - TASKS_PATH=./tasks/*.py
#    ports:
#      - "8080:8080"    # Only enable when accessing directly (without reverse proxy)
    volumes:
      - /home/pi/edgar/device-config.json:/device-config.json:ro
      - /home/pi/edgar/dashboards:/dashboards:ro
    restart: always
    networks:
      - raspberry-pi-network
    command: ["--deviceConfig", "/device-config.json", "--dashboard", "/dashboards/demo.json"]

networks:
  raspberry-pi-network:
    name: raspberry-pi-network