package com.github.rskupnik.edgar.assistant.task;

import java.util.HashMap;
import java.util.Map;

public record TaskRegistration(String command, Class<? extends Task> task, Map<String, Object> params) {

    // Primary constructor (generated by the record)
    public TaskRegistration(String command, Class<? extends Task> task, Map<String, Object> params) {
        this.command = command;
        this.task = task;
        this.params = params != null ? params : new HashMap<>();
    }

    // Secondary constructor with default params
    public TaskRegistration(String command, Class<? extends Task> task) {
        this(command, task, new HashMap<>());
    }
}
