devices:
  rediscoverUnresponsiveDevices:
    delay: 60000
    initialDelay: 60000

assistant:
  enabled: true

spring:
  config:
    import: classpath:assistant-config.yml

server:
  port: 8080

---
# Local MacOS profile
spring:
  config:
    activate:
      on-profile: local-macos