# Default profile - Raspberry Pi
tasks:
  python-executable-path: /app/tasks/venv/bin/python
  check-tauron-power-bill:
    script-location: /app/tasks/check-tauron-bill.py
    pipe: /tmp/check-tauron-power-bill
  pay-tauron-power-bill:
    script-location: /app/tasks/pay-tauron-bill.py
    pipe: /tmp/pay-tauron-power-bill
  test-driver-license:
    script-location: /app/tasks/driver-license-test.py
    pipe: /tmp/test-driver-license
    n8n:
      url: http://n8n:5678
      webhook-path: /webhook/driver-license-response

---
# Local MacOS profile
spring:
  config:
    activate:
      on-profile: local-macos

tasks:
  python-executable-path: /Users/myzek/workspace/priv/edgar2/assistant/playwright-tasks/venv/bin/python
  check-tauron-power-bill:
    script-location: /Users/myzek/workspace/priv/edgar2/assistant/playwright-tasks/check-tauron-bill.py
  pay-tauron-power-bill:
    script-location: /Users/myzek/workspace/priv/edgar2/assistant/playwright-tasks/pay-tauron-bill.py
  test-driver-license:
    script-location: /Users/myzek/workspace/priv/edgar2/assistant/playwright-tasks/driver-license-test.py
    n8n-url: http://n8n.home

---
# Local Dell profile
spring:
  config:
    activate:
      on-profile: local-dell

tasks:
  python-executable-path: /home/rskupnik/workspace/priv/edgar2/assistant/playwright-tasks/venv/bin/python
  check-tauron-power-bill:
    script-location: /home/rskupnik/workspace/priv/edgar2/assistant/playwright-tasks/check-tauron-bill.py
  pay-tauron-power-bill:
    script-location: /home/rskupnik/workspace/priv/edgar2/assistant/playwright-tasks/pay-tauron-bill.py