name: Build & Deploy
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ether-runner-edgar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build
      
      - name: Set up Docker Buildx
        run: docker buildx create --use

      - name: Build Docker Image
        run: |
          docker buildx build \
            --build-arg JAR_SOURCE_PATH=./app/build/libs/app.jar \
            --build-arg TASKS_PATH="./assistant/playwright-tasks/*.py" \
            --cache-from type=local,src=/mnt/docker-cache \
            --cache-to type=local,dest=/mnt/docker-cache \
            --load \
            -t edgar \
            -f Dockerfile .
      
      - name: Push Docker image
        run: |
          export DOCKER_CONFIG=/tmp/docker-config
          docker tag edgar rskupnik/ether:edgar
          docker push rskupnik/ether:edgar

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.33.2'
      
      - name: Restart deployment with annotation
        run: |
          kubectl patch deployment edgar \
            -n edgar \
            -p "{\"spec\":{\"template\":{\"metadata\":{\"annotations\":{\"ci-restart-timestamp\":\"$(date +%s)\"}}}}}"
