name: Build & Deploy
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ether-runner-edgar
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Grant execute permission to Gradle wrapper
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Docker image
        run: |
          docker build \
            --build-arg JAR_SOURCE_PATH=./app/build/libs/app.jar \
            --build-arg TASKS_PATH="./assistant/playwright-tasks/*.py" \
            -t edgar .
      
      - name: Push Docker image
        run: |
          docker tag edgar rskupnik/ether:edgar
          docker push rskupnik/ether:edgar